### PR TITLE
Laravel 8.0 support

### PR DESCRIPTION
**Pull request by basepack**

### CODE REVIEW

**Comment by basepack** [comment]
@hpolthof could you please merge this pull request for PHP 8 support?

**Comment by hpolthof** [comment]
Didn't see this one earlier. Will merge it! Thanks!

**Comment by basepack** [comment]
@hpolthof thanks for the merge! Could you also merge https://github.com/hpolthof/postcode-tech/pull/1 while your on it?

Goed weekend Paul! :)

**Comment by hpolthof** [comment]
Whoops, fixed!

**Pull request merged**
